-- CREATING THE EMP TABLE

CREATE TABLE EMP
(EMPNO NUMBER(4,0) NOT NULL, 
ENAME VARCHAR2(50), 
JOB VARCHAR2(50), 
MGR NUMBER(4,0), 
HIREDATE DATE, 
SAL NUMBER(7,2), 
COMM NUMBER(7,2), 
DEPTNO NUMBER(2,0));

-- CREATING THE DEPT TABLE

CREATE TABLE DEPT
(DEPTNO NUMBER(2,0) NOT NULL, 
DNAME VARCHAR2(50), 
LOC VARCHAR2(50));


